// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

type ValueType int

const (
	TypeInt ValueType = iota
	TypeFloat
	TypeString
	TypeBoolean
	TypeNull
)

type Value struct {
	Type    ValueType
	Int     int32
	Float   float64
	String  string
	Boolean bool
}

var variables map[string]Value

func init() {
	variables = make(map[string]Value)
}

func setValue(name string, value Value) {
	variables[name] = value
}

func getValue(name string) (Value, error) {
	if v, ok := variables[name]; ok {
		return v, nil
	}
	return Value{}, errors.New("undefined variable: " + name)
}

func toFloat64(v Value) float64 {
	switch v.Type {
	case TypeInt:
		return float64(v.Int)
	case TypeFloat:
		return v.Float
	default:
		return 0
	}
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Program",
			pos:  position{line: 57, col: 1, offset: 824},
			expr: &oneOrMoreExpr{
				pos: position{line: 57, col: 12, offset: 835},
				expr: &ruleRefExpr{
					pos:  position{line: 57, col: 12, offset: 835},
					name: "Statement",
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 59, col: 1, offset: 847},
			expr: &choiceExpr{
				pos: position{line: 59, col: 14, offset: 860},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 59, col: 14, offset: 860},
						name: "SetStmt",
					},
					&ruleRefExpr{
						pos:  position{line: 59, col: 24, offset: 870},
						name: "DefStmt",
					},
					&ruleRefExpr{
						pos:  position{line: 59, col: 34, offset: 880},
						name: "IfStmt",
					},
					&seqExpr{
						pos: position{line: 59, col: 43, offset: 889},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 59, col: 43, offset: 889},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 59, col: 45, offset: 891},
								expr: &ruleRefExpr{
									pos:  position{line: 59, col: 45, offset: 891},
									name: "CommentLine",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SetStmt",
			pos:  position{line: 61, col: 1, offset: 905},
			expr: &actionExpr{
				pos: position{line: 61, col: 12, offset: 916},
				run: (*parser).callonSetStmt1,
				expr: &seqExpr{
					pos: position{line: 61, col: 12, offset: 916},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 61, col: 12, offset: 916},
							val:        "Set",
							ignoreCase: false,
							want:       "\"Set\"",
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 18, offset: 922},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 61, col: 20, offset: 924},
							label: "varName",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 28, offset: 932},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 39, offset: 943},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 61, col: 41, offset: 945},
							val:        "to",
							ignoreCase: false,
							want:       "\"to\"",
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 46, offset: 950},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 61, col: 48, offset: 952},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 53, offset: 957},
								name: "Expression",
							},
						},
						&labeledExpr{
							pos:   position{line: 61, col: 64, offset: 968},
							label: "asType",
							expr: &zeroOrOneExpr{
								pos: position{line: 61, col: 71, offset: 975},
								expr: &seqExpr{
									pos: position{line: 61, col: 72, offset: 976},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 61, col: 72, offset: 976},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 61, col: 74, offset: 978},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 61, col: 79, offset: 983},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 61, col: 81, offset: 985},
											name: "DataType",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 92, offset: 996},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 61, col: 94, offset: 998},
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 94, offset: 998},
								name: "CommentLine",
							},
						},
					},
				},
			},
		},
		{
			name: "DefStmt",
			pos:  position{line: 82, col: 1, offset: 1516},
			expr: &actionExpr{
				pos: position{line: 82, col: 12, offset: 1527},
				run: (*parser).callonDefStmt1,
				expr: &seqExpr{
					pos: position{line: 82, col: 12, offset: 1527},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 82, col: 12, offset: 1527},
							val:        "Def",
							ignoreCase: false,
							want:       "\"Def\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 18, offset: 1533},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 20, offset: 1535},
							label: "varName",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 28, offset: 1543},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 39, offset: 1554},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 82, col: 41, offset: 1556},
							val:        "as",
							ignoreCase: false,
							want:       "\"as\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 46, offset: 1561},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 48, offset: 1563},
							label: "dataType",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 57, offset: 1572},
								name: "DataType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 66, offset: 1581},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 82, col: 68, offset: 1583},
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 68, offset: 1583},
								name: "CommentLine",
							},
						},
					},
				},
			},
		},
		{
			name: "IfStmt",
			pos:  position{line: 100, col: 1, offset: 2036},
			expr: &actionExpr{
				pos: position{line: 100, col: 11, offset: 2046},
				run: (*parser).callonIfStmt1,
				expr: &seqExpr{
					pos: position{line: 100, col: 11, offset: 2046},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 100, col: 11, offset: 2046},
							val:        "If",
							ignoreCase: false,
							want:       "\"If\"",
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 16, offset: 2051},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 100, col: 18, offset: 2053},
							label: "condition",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 28, offset: 2063},
								name: "Condition",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 38, offset: 2073},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 100, col: 40, offset: 2075},
							val:        "then",
							ignoreCase: false,
							want:       "\"then\"",
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 47, offset: 2082},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 100, col: 49, offset: 2084},
							label: "thenExpr",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 58, offset: 2093},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 69, offset: 2104},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 100, col: 71, offset: 2106},
							val:        "else",
							ignoreCase: false,
							want:       "\"else\"",
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 78, offset: 2113},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 100, col: 80, offset: 2115},
							label: "elseExpr",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 89, offset: 2124},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 100, offset: 2135},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 100, col: 102, offset: 2137},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&ruleRefExpr{
							pos:  position{line: 100, col: 106, offset: 2141},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 100, col: 108, offset: 2143},
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 108, offset: 2143},
								name: "CommentLine",
							},
						},
					},
				},
			},
		},
		{
			name: "Condition",
			pos:  position{line: 111, col: 1, offset: 2349},
			expr: &actionExpr{
				pos: position{line: 111, col: 14, offset: 2362},
				run: (*parser).callonCondition1,
				expr: &seqExpr{
					pos: position{line: 111, col: 14, offset: 2362},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 111, col: 14, offset: 2362},
							label: "varName",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 22, offset: 2370},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 33, offset: 2381},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 111, col: 35, offset: 2383},
							val:        "is",
							ignoreCase: false,
							want:       "\"is\"",
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 40, offset: 2388},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 111, col: 42, offset: 2390},
							val:        "Null",
							ignoreCase: false,
							want:       "\"Null\"",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 119, col: 1, offset: 2536},
			expr: &choiceExpr{
				pos: position{line: 119, col: 15, offset: 2550},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 119, col: 15, offset: 2550},
						name: "ArithmeticExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 119, col: 32, offset: 2567},
						name: "FunctionCall",
					},
					&ruleRefExpr{
						pos:  position{line: 119, col: 47, offset: 2582},
						name: "Value",
					},
				},
			},
		},
		{
			name: "ArithmeticExpr",
			pos:  position{line: 121, col: 1, offset: 2589},
			expr: &choiceExpr{
				pos: position{line: 121, col: 19, offset: 2607},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 121, col: 19, offset: 2607},
						run: (*parser).callonArithmeticExpr2,
						expr: &seqExpr{
							pos: position{line: 121, col: 19, offset: 2607},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 121, col: 19, offset: 2607},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 24, offset: 2612},
										name: "Term",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 29, offset: 2617},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 31, offset: 2619},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 121, col: 35, offset: 2623},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 121, col: 35, offset: 2623},
												val:        "+",
												ignoreCase: false,
												want:       "\"+\"",
											},
											&litMatcher{
												pos:        position{line: 121, col: 41, offset: 2629},
												val:        "-",
												ignoreCase: false,
												want:       "\"-\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 46, offset: 2634},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 121, col: 48, offset: 2636},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 121, col: 54, offset: 2642},
										name: "Expression",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 136, col: 7, offset: 3080},
						name: "Term",
					},
				},
			},
		},
		{
			name: "Term",
			pos:  position{line: 138, col: 1, offset: 3086},
			expr: &choiceExpr{
				pos: position{line: 138, col: 9, offset: 3094},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 138, col: 9, offset: 3094},
						run: (*parser).callonTerm2,
						expr: &seqExpr{
							pos: position{line: 138, col: 9, offset: 3094},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 138, col: 9, offset: 3094},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 138, col: 14, offset: 3099},
										name: "Factor",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 138, col: 21, offset: 3106},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 138, col: 23, offset: 3108},
									label: "op",
									expr: &choiceExpr{
										pos: position{line: 138, col: 27, offset: 3112},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 138, col: 27, offset: 3112},
												val:        "*",
												ignoreCase: false,
												want:       "\"*\"",
											},
											&litMatcher{
												pos:        position{line: 138, col: 33, offset: 3118},
												val:        "/",
												ignoreCase: false,
												want:       "\"/\"",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 138, col: 38, offset: 3123},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 138, col: 40, offset: 3125},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 138, col: 46, offset: 3131},
										name: "Term",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 153, col: 7, offset: 3563},
						name: "Factor",
					},
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 155, col: 1, offset: 3571},
			expr: &choiceExpr{
				pos: position{line: 155, col: 11, offset: 3581},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 155, col: 11, offset: 3581},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 155, col: 11, offset: 3581},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 155, col: 11, offset: 3581},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 155, col: 15, offset: 3585},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 155, col: 17, offset: 3587},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 155, col: 22, offset: 3592},
										name: "Expression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 155, col: 33, offset: 3603},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 155, col: 35, offset: 3605},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 156, col: 7, offset: 3636},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 157, col: 7, offset: 3649},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 158, col: 7, offset: 3669},
						name: "BooleanLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 159, col: 7, offset: 3690},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 161, col: 1, offset: 3702},
			expr: &choiceExpr{
				pos: position{line: 161, col: 11, offset: 3712},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 161, col: 11, offset: 3712},
						run: (*parser).callonNumber2,
						expr: &labeledExpr{
							pos:   position{line: 161, col: 11, offset: 3712},
							label: "float",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 17, offset: 3718},
								name: "FloatLiteral",
							},
						},
					},
					&actionExpr{
						pos: position{line: 165, col: 7, offset: 3841},
						run: (*parser).callonNumber5,
						expr: &labeledExpr{
							pos:   position{line: 165, col: 7, offset: 3841},
							label: "integer",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 15, offset: 3849},
								name: "IntegerLiteral",
							},
						},
					},
				},
			},
		},
		{
			name: "FloatLiteral",
			pos:  position{line: 170, col: 1, offset: 3964},
			expr: &actionExpr{
				pos: position{line: 170, col: 17, offset: 3980},
				run: (*parser).callonFloatLiteral1,
				expr: &seqExpr{
					pos: position{line: 170, col: 17, offset: 3980},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 170, col: 17, offset: 3980},
							expr: &charClassMatcher{
								pos:        position{line: 170, col: 17, offset: 3980},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&litMatcher{
							pos:        position{line: 170, col: 24, offset: 3987},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 170, col: 28, offset: 3991},
							expr: &charClassMatcher{
								pos:        position{line: 170, col: 28, offset: 3991},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "IntegerLiteral",
			pos:  position{line: 172, col: 1, offset: 4030},
			expr: &actionExpr{
				pos: position{line: 172, col: 19, offset: 4048},
				run: (*parser).callonIntegerLiteral1,
				expr: &oneOrMoreExpr{
					pos: position{line: 172, col: 19, offset: 4048},
					expr: &charClassMatcher{
						pos:        position{line: 172, col: 19, offset: 4048},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 174, col: 1, offset: 4087},
			expr: &actionExpr{
				pos: position{line: 174, col: 18, offset: 4104},
				run: (*parser).callonStringLiteral1,
				expr: &seqExpr{
					pos: position{line: 174, col: 18, offset: 4104},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 174, col: 18, offset: 4104},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 174, col: 22, offset: 4108},
							expr: &seqExpr{
								pos: position{line: 174, col: 23, offset: 4109},
								exprs: []any{
									&notExpr{
										pos: position{line: 174, col: 23, offset: 4109},
										expr: &litMatcher{
											pos:        position{line: 174, col: 24, offset: 4110},
											val:        "\"",
											ignoreCase: false,
											want:       "\"\\\"\"",
										},
									},
									&anyMatcher{
										line: 174, col: 28, offset: 4114,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 174, col: 32, offset: 4118},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "BooleanLiteral",
			pos:  position{line: 178, col: 1, offset: 4208},
			expr: &actionExpr{
				pos: position{line: 178, col: 19, offset: 4226},
				run: (*parser).callonBooleanLiteral1,
				expr: &choiceExpr{
					pos: position{line: 178, col: 20, offset: 4227},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 178, col: 20, offset: 4227},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&litMatcher{
							pos:        position{line: 178, col: 29, offset: 4236},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 183, col: 1, offset: 4349},
			expr: &actionExpr{
				pos: position{line: 183, col: 15, offset: 4363},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 183, col: 15, offset: 4363},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 183, col: 15, offset: 4363},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 183, col: 23, offset: 4371},
							expr: &charClassMatcher{
								pos:        position{line: 183, col: 23, offset: 4371},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DataType",
			pos:  position{line: 187, col: 1, offset: 4420},
			expr: &choiceExpr{
				pos: position{line: 187, col: 13, offset: 4432},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 187, col: 13, offset: 4432},
						val:        "Integer",
						ignoreCase: false,
						want:       "\"Integer\"",
					},
					&litMatcher{
						pos:        position{line: 187, col: 25, offset: 4444},
						val:        "Float",
						ignoreCase: false,
						want:       "\"Float\"",
					},
					&litMatcher{
						pos:        position{line: 187, col: 35, offset: 4454},
						val:        "String",
						ignoreCase: false,
						want:       "\"String\"",
					},
					&litMatcher{
						pos:        position{line: 187, col: 46, offset: 4465},
						val:        "Boolean",
						ignoreCase: false,
						want:       "\"Boolean\"",
					},
				},
			},
		},
		{
			name: "FunctionCall",
			pos:  position{line: 189, col: 1, offset: 4476},
			expr: &actionExpr{
				pos: position{line: 189, col: 17, offset: 4492},
				run: (*parser).callonFunctionCall1,
				expr: &seqExpr{
					pos: position{line: 189, col: 17, offset: 4492},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 189, col: 17, offset: 4492},
							val:        "Print",
							ignoreCase: false,
							want:       "\"Print\"",
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 25, offset: 4500},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 189, col: 27, offset: 4502},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 31, offset: 4506},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 189, col: 33, offset: 4508},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 189, col: 38, offset: 4513},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 189, col: 49, offset: 4524},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 189, col: 51, offset: 4526},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "CommentLine",
			pos:  position{line: 209, col: 1, offset: 4980},
			expr: &seqExpr{
				pos: position{line: 209, col: 16, offset: 4995},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 209, col: 16, offset: 4995},
						val:        "#",
						ignoreCase: false,
						want:       "\"#\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 209, col: 20, offset: 4999},
						expr: &charClassMatcher{
							pos:        position{line: 209, col: 20, offset: 4999},
							val:        "[^\\n]",
							chars:      []rune{'\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 211, col: 1, offset: 5007},
			expr: &zeroOrMoreExpr{
				pos: position{line: 211, col: 19, offset: 5025},
				expr: &charClassMatcher{
					pos:        position{line: 211, col: 19, offset: 5025},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onSetStmt1(varName, expr, asType any) (any, error) {
	value, ok := expr.(Value)
	if !ok {
		return nil, errors.New("invalid expression")
	}
	if asType != nil {
		dataType := asType.([]interface{})[3]
		switch dataType.(string) {
		case "Integer":
			value.Type = TypeInt
			value.Int = int32(value.Float)
		case "String":
			value.Type = TypeString
		case "Boolean":
			value.Type = TypeBoolean
		}
	}
	setValue(varName.(string), value)
	return nil, nil
}

func (p *parser) callonSetStmt1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSetStmt1(stack["varName"], stack["expr"], stack["asType"])
}

func (c *current) onDefStmt1(varName, dataType any) (any, error) {
	var value Value
	switch dataType.(string) {
	case "Integer":
		value = Value{Type: TypeInt}
	case "Float":
		value = Value{Type: TypeFloat}
	case "String":
		value = Value{Type: TypeString}
	case "Boolean":
		value = Value{Type: TypeBoolean}
	default:
		return nil, errors.New("unsupported type: " + dataType.(string))
	}
	setValue(varName.(string), value)
	return nil, nil
}

func (p *parser) callonDefStmt1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefStmt1(stack["varName"], stack["dataType"])
}

func (c *current) onIfStmt1(condition, thenExpr, elseExpr any) (any, error) {
	condValue, ok := condition.(bool)
	if !ok {
		return nil, errors.New("invalid condition")
	}
	if condValue {
		return thenExpr, nil
	}
	return elseExpr, nil
}

func (p *parser) callonIfStmt1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIfStmt1(stack["condition"], stack["thenExpr"], stack["elseExpr"])
}

func (c *current) onCondition1(varName any) (any, error) {
	value, err := getValue(varName.(string))
	if err != nil {
		return nil, err
	}
	return value.Type == TypeNull, nil
}

func (p *parser) callonCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCondition1(stack["varName"])
}

func (c *current) onArithmeticExpr2(left, op, right any) (any, error) {
	leftValue, ok1 := left.(Value)
	rightValue, ok2 := right.(Value)
	if !ok1 || !ok2 {
		return nil, errors.New("invalid arithmetic operands")
	}
	result := Value{Type: TypeFloat}
	switch op.(string) {
	case "+":
		result.Float = toFloat64(leftValue) + toFloat64(rightValue)
	case "-":
		result.Float = toFloat64(leftValue) - toFloat64(rightValue)
	}
	return result, nil
}

func (p *parser) callonArithmeticExpr2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArithmeticExpr2(stack["left"], stack["op"], stack["right"])
}

func (c *current) onTerm2(left, op, right any) (any, error) {
	leftValue, ok1 := left.(Value)
	rightValue, ok2 := right.(Value)
	if !ok1 || !ok2 {
		return nil, errors.New("invalid arithmetic operands")
	}
	result := Value{Type: TypeFloat}
	switch op.(string) {
	case "*":
		result.Float = toFloat64(leftValue) * toFloat64(rightValue)
	case "/":
		result.Float = toFloat64(leftValue) / toFloat64(rightValue)
	}
	return result, nil
}

func (p *parser) callonTerm2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerm2(stack["left"], stack["op"], stack["right"])
}

func (c *current) onFactor2(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonFactor2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["expr"])
}

func (c *current) onNumber2(float any) (any, error) {
	f, _ := strconv.ParseFloat(float.(string), 64)
	return Value{Type: TypeFloat, Float: f}, nil
}

func (p *parser) callonNumber2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber2(stack["float"])
}

func (c *current) onNumber5(integer any) (any, error) {
	i, _ := strconv.Atoi(integer.(string))
	return Value{Type: TypeInt, Int: int32(i)}, nil
}

func (p *parser) callonNumber5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber5(stack["integer"])
}

func (c *current) onFloatLiteral1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFloatLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatLiteral1()
}

func (c *current) onIntegerLiteral1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIntegerLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntegerLiteral1()
}

func (c *current) onStringLiteral1() (any, error) {
	return Value{Type: TypeString, String: string(c.text[1 : len(c.text)-1])}, nil
}

func (p *parser) callonStringLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral1()
}

func (c *current) onBooleanLiteral1() (any, error) {
	b, _ := strconv.ParseBool(string(c.text))
	return Value{Type: TypeBoolean, Boolean: b}, nil
}

func (p *parser) callonBooleanLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBooleanLiteral1()
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onFunctionCall1(expr any) (any, error) {
	value, ok := expr.(Value)
	if !ok {
		return nil, errors.New("invalid print argument")
	}
	switch value.Type {
	case TypeInt:
		fmt.Printf("%d\n", value.Int)
	case TypeFloat:
		fmt.Printf("%f\n", value.Float)
	case TypeString:
		fmt.Printf("%s\n", value.String)
	case TypeBoolean:
		fmt.Printf("%t\n", value.Boolean)
	case TypeNull:
		fmt.Println("Null")
	}
	return nil, nil
}

func (p *parser) callonFunctionCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionCall1(stack["expr"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
